//
// Created by temTeng on 2021/7/20.
//

#ifndef DATASTRUCTUREANDALGORITHMINCPP_THREADEDBINARYTREETEST_H
#define DATASTRUCTUREANDALGORITHMINCPP_THREADEDBINARYTREETEST_H


class ThreadedBinaryTreeTest {
public:
    static void test();

};


#endif //DATASTRUCTUREANDALGORITHMINCPP_THREADEDBINARYTREETEST_H
